kind: Deployment
apiVersion: apps/v1
metadata:
  name: mc-ui
  labels:
    app: mc-ui
    app.kubernetes.io/part-of: mission-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mc-ui
  template:
    metadata:
      labels:
        app: mc-ui
    spec:
      containers:
        - name: mc-ui
          image: 'quay.io/wael2000/mc-ui:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: battalionService.url
              value: mc-route-demo.apps.cluster-f44mq.dynamic.redhatworkshops.io
            - name: ocp.api.url
              value: 'https://api.cluster-f44mq.dynamic.redhatworkshops.io:6443'
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: mc-ui
  labels:
    app: mc-ui
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: mc-ui
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: mc-ui-route
  labels:
    app: mc-ui
spec:
  to:
    kind: Service
    name: mc-ui
  port:
    targetPort: 8080-tcp