kind: Deployment
apiVersion: apps/v1
metadata:
  name: apis
  labels:
    app: apis
    app.kubernetes.io/part-of: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apis
  template:
    metadata:
      labels:
        app: apis
    spec:
      volumes:
        - name: data-volume
          configMap:
            name: db-config
            defaultMode: 420
      initContainers:
        - name: init-createdb
          image: 'postgres:14'
          command:
            - psql
            - 'postgresql://postgres:postgres@postgresql'
            - '-f'
            - /etc/dbvolume/create_database.sql
          resources: {}
          volumeMounts:
            - name: data-volume
              mountPath: /etc/dbvolume
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: init-builddb
          image: 'postgres:14'
          command:
            - psql
            - 'postgresql://postgres:postgres@postgresql/battalion'
            - '-f'
            - /etc/dbvolume/build_tables.sql
          resources: {}
          volumeMounts:
            - name: data-volume
              mountPath: /etc/dbvolume
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: init-populatedb
          image: 'postgres:14'
          command:
            - psql
            - 'postgresql://postgres:postgres@postgresql/battalion'
            - '-f'
            - /etc/dbvolume/data.sql
          resources: {}
          volumeMounts:
            - name: data-volume
              mountPath: /etc/dbvolume
          imagePullPolicy: IfNotPresent
      containers:
        - name: apis
          image: 'image-registry.openshift-image-registry.svc:5000/demo/apis:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: battalion
              value: '1'
            - name: location
              value: DC
            - name: system
              value: Fixed-Wing
            - name: cors.origin
              value: 'http://ui-route-demo.apps.cluster-f44mq.dynamic.redhatworkshops.io'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600