kind: Deployment
apiVersion: apps/v1
metadata:
  name: apis
  labels:
    app: apis
    app.kubernetes.io/part-of: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apis
  template:
    metadata:
      labels:
        app: apis
    spec:
      containers:
        - name: apis
          image: 'quay.io/wael2000/apis:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: location
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: location
            - name: battalion
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: battalion
            - name: system
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: system
            - name: battalion1
              value: '1'
            - name: location1
              value: DC
            - name: system1
              value: Fixed-Wing
            - name: cors.origin
              value: 'http://dummy'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600