kind: Deployment
apiVersion: apps/v1
metadata:
  name: apis
  labels:
    app: apis
    app.kubernetes.io/part-of: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apis
  template:
    metadata:
      labels:
        app: apis
    spec:
      containers:
        - name: apis
          image: 'image-registry.openshift-image-registry.svc:5000/openshift/apis:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: battalion
              value: '1'
            - name: location
              value: DC
            - name: system
              value: Fixed-Wing
            - name: cors.origin
              value: 'http://ui-route-mc.apps.cluster-f44mq.dynamic.redhatworkshops.io'
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600