apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
replacements:
- source:
      kind: ConfigMap
      name: app-config
      fieldPath: location
  targets:
    - select:
        kind: Deployment
        name: apis
      fieldPaths:
        - spec.template.spec.containers.[name=apis].env.[name=location].value