kind: Service
apiVersion: v1
metadata:
  name: postgresqldb
  annotations:
    argocd.argoproj.io/sync-wave: "2"  
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: postgresqldb
      protocol: TCP
      port: 5432
      targetPort: 5432
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    name: postgresql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-config
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6   
  template:         
    metadata:
      name: db-config
    spec:
      volumes:
        - name: data-volume
          configMap:
            name: db-config
            defaultMode: 420    
      containers:
      - name: init-createdb
        image: 'postgres:14'
        command:
          - psql
          - 'postgresql://postgres:postgres@postgresqldb'
          - '-f'
          - /etc/dbvolume/create_database.sql
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: init-builddb
        image: 'postgres:14'
        command: ["/bin/sh","-c"]
        args: ["sleep 5; psql postgresql://postgres:postgres@postgresqldb/battalion -f /etc/dbvolume/build_tables.sql"]
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: init-populatedb
        image: 'postgres:14'
        command: ["/bin/sh","-c"]
        args: ["sleep 10; psql postgresql://postgres:postgres@postgresqldb/battalion -f /etc/dbvolume/data.sql"]
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: init-populateConfig
        image: 'postgres:14'
        command: ["/bin/sh","-c"]
        args: ["sleep 10; psql postgresql://postgres:postgres@postgresqldb/battalion -f /etc/dbvolume/config.sql"]
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent        
      restartPolicy: OnFailure  