apiVersion: batch/v1
kind: Job
metadata:
  name: db-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "3"  
spec:
  parallelism: 1    
  completions: 1    
  activeDeadlineSeconds: 1800 
  backoffLimit: 6   
  template:         
    metadata:
      name: db-config
    spec:
      volumes:
        - name: data-volume
          configMap:
            name: db-config
            defaultMode: 420    
      containers:
      - name: init-createdb
        image: 'postgres:14'
        command:
          - psql
          - 'postgresql://postgres:postgres@postgresqldb'
          - '-f'
          - /etc/dbvolume/create_database.sql
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: init-builddb
        image: 'postgres:14'
        command: ["/bin/sh","-c"]
        args: ["sleep 3; psql postgresql://postgres:postgres@postgresqldb/battalion -f /etc/dbvolume/build_tables.sql"]
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: init-populatedb
        image: 'postgres:14'
        command: ["/bin/sh","-c"]
        args: ["sleep 6; psql postgresql://postgres:postgres@postgresqldb/battalion -f /etc/dbvolume/data.sql"]
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
      - name: init-populateConfig
        image: 'postgres:14'
        command: ["/bin/sh","-c"]
        args: ["sleep 9; psql postgresql://postgres:postgres@postgresqldb/battalion -f /etc/dbvolume/config.sql"]
        resources: {}
        volumeMounts:
          - name: data-volume
            mountPath: /etc/dbvolume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent        
      restartPolicy: OnFailure  