apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - system=Fire-Support
  - app_name=fire-support