apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../apis
- ../../ui
configMapGenerator:
- name: app-config
  literals:
  - battalion=1
  - location=AWS
  - system=Rotay-Wing
  - app_name=rotary-wing
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: rotary-wing-apis
  target:
    name: apis
- patch: |-
    - op: replace
      path: /metadata/name
      value: rotary-wing-ui
  target:
    name: ui
- patch: |-
    - op: replace
      path: /spec/to/name
      value: rotary-wing-ui
  target:
    kind: Route
    name: ui
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/env/0/value 
      value: rotary-wing-apis
  target:
    kind: Deployment
    name: ui