apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLServer
metadata:
  name: postgresqlserver-battalion
spec:
  location: eastus
  resourceGroup: openenv-fxgmd
  serverVersion: "10"
  sslEnforcement: Enabled
  replicaProperties: {}
  sku:
    name: B_Gen5_2
    tier: Basic
    family: Gen5
    size: "51200"
    capacity: 2
  # Use the field below to optionally specify a different keyvault 
  # to store the server admin credential secrets in
  #keyVaultToStoreSecrets: asoSecretKeyVault
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: battalion
spec:
  resourceGroup: openenv-fxgmd
  server: postgresqlserver-battalion
---
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLFirewallRule
metadata:
  name: postgresqlfirewallrule-battalion
spec:
  resourceGroup: openenv-fxgmd
  server: postgresqlserver-battalion
  startIpAddress: 0.0.0.0
  endIpAddress: 255.255.255.255