apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../kustomization.yaml
configMapGenerator:
- name: app-config
  literals:
  - battalion_id=4
  - battalion=mes
  - location=Azure
  - system=Fire-Support
  - app_name=fire-support