apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
configMapGenerator:
- name: app-config
  behavior: merge
  literals:
  - battalion_id=1
  - battalion=fox
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
  target:
    group: apps
    kind: Deployment
    name: apis
    version: v1  