apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: azure-trigger-binding
spec:
  params:
    - name: battalion
      value: $(body.battalion)
    - name: action
      value: $(body.action)