apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: battalion-ops
spec:
  params:
    - default: fox-team
      description: battalion name
      name: battalion
      type: string
    - default: deploy
      description: action
      name: action
      type: string
    - default: fixed-wing
      name: app_name
      type: string
    - default: dc
      name: location
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/wael2000/mission-command'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:9b14f52b21d29d8d83ea4c0e78623debc954f1a732d2be6d1a7269fbba23b1a4'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: deploy-app
      params:
        - name: SCRIPT
          value: sed -e 's/BATTALION/$(params.battalion)/g' -e 's/APP_NAME/$(params.app_name)/g' -e 's/LOCATION/$(params.location)/g' gitops/ops-application.yaml | oc create -f - -n openshift-gitops
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: remove-the-app
      params:
        - name: SCRIPT
          value: 'oc delete application $(params.battalion)-$(params.app_name) -n openshift-gitops '
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - remove
      workspaces:
        - name: manifest-dir
          workspace: source
  workspaces:
    - name: source
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: battalion-ops-trigger-binding
spec:
  params:
    - name: battalion
      value: $(body.battalion)
    - name: action
      value: $(body.action)
    - name: app_name
      value: $(body.app_name)
    - name: location
      value: $(body.location)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: battalion-ops-trigger-template
spec:
  params:
    - description: battalion name
      name: battalion
    - description: action
      name: action
    - name: app_name
      description: app_name
    - name: location
      description: location
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: battalion-pipeline-$(tt.params.battalion)-
      spec:
        params:
          - name: battalion
            value: $(tt.params.battalion)
          - name: app_name
            value: $(tt.params.app_name) 
          - name: action
            value: $(tt.params.action)
          - name: location
            value: $(tt.params.location)
        pipelineRef:
          name: battalion-ops
        serviceAccountName: pipeline
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 128Mi
                storageClassName: ocs-external-storagecluster-ceph-rbd
                volumeMode: Filesystem
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: battalion-ops-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: battalion-ops-trigger-binding
      name: battalion-trigger
      template:
        ref: battalion-ops-trigger-template