apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: battalion-deploy-team
spec:
  params:
    - default: fox-team
      description: battalion name
      name: battalion
      type: string
    - default: deploy
      description: action
      name: action
      type: string
    - default: dc
      name: location
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/wael2000/mission-command'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: 'registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:9b14f52b21d29d8d83ea4c0e78623debc954f1a732d2be6d1a7269fbba23b1a4'
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: create-workspace
      params:
        - name: SCRIPT
          value: 'oc new-project battalion-$(params.battalion) '
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
    - name: add-to-manage-scope
      params:
        - name: SCRIPT
          value: oc label ns battalion-$(params.battalion) argocd.argoproj.io/managed-by=openshift-gitops
        - name: VERSION
          value: latest
      runAfter:
        - create-workspace
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: provision-db
      params:
        - name: SCRIPT
          value: sed -e 's/BATTALION/$(params.battalion)/g' -e 's/LOCATION/$(params.location)/g' gitops/db-application.yaml | oc create -f - -n openshift-gitops
        - name: VERSION
          value: latest
      runAfter:
        - add-to-manage-scope
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: remove-the-app
      params:
        - name: SCRIPT
          value: oc delete application $(params.battalion)-db -n openshift-gitops | oc delete project  battalion-$(params.battalion)
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - remove
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: expose-db
      params:
        - name: SCRIPT
          value: oc create -f gitops/db/base/db-service.yaml -n battalion-$(params.battalion)
        - name: VERSION
          value: latest
      runAfter:
        - provision-db
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
      workspaces:
        - name: manifest-dir
          workspace: source
    - name: install-skupper
      params:
        - name: SCRIPT
          value: oc create configmap skupper-site --from-literal=name=$(params.location)-site --from-literal=console=true --from-literal=flow-collector=true --from-literal=console-authentication=unsecured -n battalion-$(params.battalion)
        - name: VERSION
          value: latest
      runAfter:
        - expose-db
      taskRef:
        kind: ClusterTask
        name: openshift-client
      when:
        - input: $(params.action)
          operator: in
          values:
            - deploy
  workspaces:
    - name: source
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: battalion-team-trigger-binding
spec:
  params:
    - name: battalion
      value: $(body.battalion)
    - name: action
      value: $(body.action)
    - name: location
      value: $(body.location)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: battalion-team-trigger-template
spec:
  params:
    - description: battalion name
      name: battalion
    - description: action
      name: action
    - name: location
      description: location
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: battalion-deploy-team-$(tt.params.battalion)-
      spec:
        params:
          - name: battalion
            value: $(tt.params.battalion)
          - name: action
            value: $(tt.params.action)
          - name: location
            value: $(tt.params.location)
        pipelineRef:
          name: battalion-deploy-team
        serviceAccountName: pipeline
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 128Mi
                storageClassName: ocs-external-storagecluster-ceph-rbd
                volumeMode: Filesystem
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: battalion-team-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: battalion-team-trigger-binding
      name: battalion-trigger
      template:
        ref: battalion-team-trigger-template