apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: battalion-team-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: battalion-team-trigger-binding
      name: battalion-trigger
      template:
        ref: battalion-team-trigger-template