apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: battalion-team-trigger-binding
spec:
  params:
    - name: battalion
      value: $(body.battalion)
    - name: action
      value: $(body.action)
    - name: location
      value: $(body.location)