apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: battalion
spec:
  destination:
    namespace: battalion
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/db
    repoURL: https://github.com/wael2000/mission-command
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true