apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-ops
spec:
  destination:
    namespace: battalion-blue
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops
    repoURL: https://github.com/wael2000/mission-command
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true